spring:
  profiles:
    active: DEV
  datasource:
    database: ctrl
    port: 5432
    driver-class-name: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/ctrl
    username: postgres
    password: password
    configuration:
      maximum-pool-size: 30
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  server:
    port: 8080
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui-custom.html
      operationSorter: method