version: "3.5"
services:
  postgres:
    container_name: postgresContainer
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ctrl'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

  app:
    container_name: jBookingService
    build: ./
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=REC"
    depends_on:
      - postgres