services:
  postgres:
    container_name: postgresContainer
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ctrl'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

  app:
    container_name: jBookingService
    build: ./
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=REC"
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres