CREATE TABLE place (
	id SERIAL PRIMARY KEY,
	created_at TIMESTAMP NOT NULL DEFAULT now(),
	address VARCHAR (150) NOT NULL,
	city VARCHAR (100) NOT NULL,
	country VARCHAR (100) NOT NULL,
	postal_code VARCHAR (20),
	free_rooms INTEGER NOT NULL,
	daily_price NUMERIC(15,2) NOT NULL DEFAULT 0
);